### ISSUE TITLE
pyretic.py: command not found

### ISSUE THREAD

**Issue by closedog** [frenetic-lang/pyretic#65]
Hi all:

i have some problem when i start the tut as i print "pyretic.py -m p0 pyretic.modules.mac_learner" , it shows "pyretic.py: command not found" . Also when i run a exisit pyfile by"sudo python xxx.py", it shows " File "hotel_ctrl.py", line 2, in <module>
    from pyretic.lib.corelib import *
ImportError: No module named pyretic.lib.corelib"
How can i start it?

Thanks in advance.
Closedog

**Comment by jacostar** [comment]
Which tutorial you have? 
Are you sure you have pyretic on it?
Try to look up at pyretic.lib.corelib to see if that module exists
(excuse my English, I´m Cuban)

**Comment by chelobarreto** [comment]
Hola, soy de Argentina sigamos en español :)

Te paso la receta:

Ubuntu 14.04 amd64 tiene que ser de 64 bits porque sino apt-get install 
frenetic no instala nada

Clonas pyretic en una carpeta

cd /root

clone https://github.com/frenetic-lang/pyretic.git

Clonas pox

clone https://github.com/noxrepo/pox.git

Luego en /root tenes las carpetas pyretic y pox

Instalas Frenetic

Agregando en /etc/apt/sources.list

|deb https://dl.bintray.com/arjunguha/deb trusty main apt-get update && 
apt-get install frenetic |

Luego en /root/.profile agregas al final

PYTHONPATH=$PYTHONPATH:$HOME/pyretic:$HOME/pox
PATH=$PATH:$HOME/pyretic:$HOME/pox
export PYTHONPATH PATH

Y luego en /root/pyretic/start-frenetic.sh cambias el ./frenetic por la 
ruta a frenetic que obtenes via
whereis frenetic

Espero que te sea de ayuda

**Comment by jacostar** [comment]
Tengo ahora una duda, para que propones instalar frenetic si el tutorial que closedog habla es de pyretic?.
Yo he utilizado bastante a pyretic con una VM que se encuentra en SDNHUB (para mí mucho mejor que la VM que propone el sitio oficial del proyecto) y solo tiene instalado pyretic, he buscado y no aparece frenetic por ningun lugar.
Saludos

**Comment by closedog** [comment]
Thanks for u answers. I finish the project by Ryu controller finally :)

**Comment by jacostar** [comment]
what was your project about?

**Comment by closedog** [comment]
Just a mini project for my course

**Comment by himanshurawlani** [comment]
root@mininet-vm:/pyretic# ./pyretic.py pyretic.pyresonance.apps.ids
Traceback (most recent call last):
File "./pyretic.py", line 313, in
main()
File "./pyretic.py", line 275, in main
write_log=options.write_log)
File "/home/mininet/pyretic/pyretic/core/runtime.py", line 87, in init
self.forwarding = main(**kwargs)
TypeError: main() takes exactly 1 argument (0 given)
root@mininet-vm:/pyretic#

I'm following this wiki : [https://github.com/Resonance-SDN/pyresonance/wiki/PyResonance-overhaul:-Running-example-applications](url)
I'm stuck here, please help...
